### ISSUE TITLE
Not compatible with Gnome 3.12

### ISSUE THREAD

**Issue by Abhinav1217** [deuill/shell-extension-quitfromdash#1]
Please update this to be compatible with Gnome 3.12.

**Comment by deuill** [comment]
I'm still on Gnome 3.10, but I'll update once I check this out on 3.12 for any issues. I'm getting mixed messages on whether it's simply an issue on updating the metadata, so I'll refrain from uploading without checking.

Thanks!

**Comment by Abhinav1217** [comment]
I updated the Metadata.json based on a comment on your page on the extensions.gnome.org website.  
 I could enable the plugin and there was a option visible to Quit applications.  But applications were not quitting when clicked.

**Comment by deuill** [comment]
Closing this as stale.
